<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>ff3f8d08-5588-4e36-9ada-475dbd9f87ce</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.Kafka" />
    <PackageReference Include="Aspire.Hosting.MongoDB" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="InfinityFlow.Aspire.Temporal" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\external\camunda-startup\CamundaStartup.Aspire.Hosting.Camunda\CamundaStartup.Aspire.Hosting.Camunda.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\..\Applications\Applications.WebApi\Applications.WebApi.csproj" />
    <ProjectReference Include="..\..\..\Calculations\Calculations.WebApi\Calculations.WebApi.csproj" />
    <ProjectReference Include="..\..\..\Front\Credit.Front.Blazor\Credit.Front.Blazor\Credit.Front.Blazor.csproj" />
    <ProjectReference Include="..\..\..\Processes\Processes.Elsa.WebApi\Processes.Elsa.WebApi.csproj" />
    <ProjectReference Include="..\..\..\Processes\Processes.Saga.WebApi\Processes.Saga.WebApi.csproj" />
    <ProjectReference Include="..\..\..\Processes\Processes.Temporal.WebApi\Processes.Temporal.WebApi.csproj" />
    <ProjectReference Include="..\..\..\Processes\Processes.Camunda.WebApi\Processes.Camunda.WebApi.csproj" />
    <ProjectReference Include="..\..\..\Processes\Processes.Conductor.WebApi\Processes.Conductor.WebApi.csproj" />

  </ItemGroup>

</Project>
